### ISSUE TITLE
Recent update broke helicopter landing pads when also using the Helicopters mod

### ISSUE THREAD

**Issue by i-r-Legion** [jpanther/Dectorio#123] opened 2019-09-11 19:08 UTC
After installing the most recent Dectorio update, it seems to have broken the landing pads for Helicopters. Upon loading my game right after the update, it notified me that 300+ helicopter tiles had been removed. Sure enough, all the landing pads were gone except for the white H with a circle around it. It seems that something was changed in the most recent dectorio update that no longer jives with Helicopters. 
![heli crash](https://user-images.githubusercontent.com/55208979/64727021-87836500-d49d-11e9-93fe-76b05b20e078.PNG)

**How to reproduce**
Have both Helicopters and Dectorio mod installed. 
Craft Heli landing pad and attempt to place on ground.
Crash game 

**Screenshots**

**Mod list**
If you are playing with other mods, include a list of these mods. The best way to do this is to provide a copy of `mod-list.json` from your Factorio data folder.

**Multiplayer**
If playing in multiplayer and you experience a desync, please upload a copy of your desync report.

**Additional context**

**Comment by jpanther** [comment] 2019-09-11 23:28
Thanks for the report. This is interesting as I myself play with both Dectorio and _Helicopters_ on my current save and I haven't come across this error. The screenshot you posted seems to be an issue in the _Helicopters_ mod though, but I'll do some testing to see if there's something in Dectorio that is causing the problem.

**Comment by jpanther** [comment] 2019-09-11 23:37
Out of interest are you playing with _Alien Biomes_? Your error looks the same as the one reported on the mod portal here: https://mods.factorio.com/mod/Helicopters/discussion/5ceb88c03301b1000be61d02

**Comment by i-r-Legion** [comment] 2019-09-19 01:02
It seems to possibly be an issue with the refined concrete tiles used on
the heli pad and the ones used in Dectorio... possibly

**Comment by i-r-Legion** [comment] 2019-09-19 01:02
Yes I am, sorry for the late reply. I forgot to mention that part

**Comment by jpanther** [comment] 2019-09-30 00:32
I've done a bit more testing on this and am still unable to replicate this error you're seeing. I can place helipads with Dectorio present and it works fine. I've also tested this with _Alien Biomes_ and Dectorio and have no problems there either. I've done further testing in my own campaign which is a complex Bobs/Angels modpack and there's no issues placing helipads there. It's either something that's being caused by another mod or it's some combination of mods in your save that is incompatible but I'm confident it's not just having Dectorio and _Helicopters_ that is causing it.

I suspect it's something to do with having too many mods that add tiles (_Alien Biomes_ uses up almost all the free tile slots in the game so if you try to add to many more modded tiles, you will have issues), but I can't say without knowing your modpack. A possible workaround to this tile issue could be to disable painted concrete in Dectorio or disable some of the biomes in the _Alien Biomes_ settings as that will reduce the number of tiles being created and may allow _Helicopters_ to work, but it's only a guess at this stage.

**Comment by jpanther** [comment] 2020-01-24 00:08
Given there's been no further discussion on this issue and Factorio 0.18 has now been released, I'm going to close this one for now.

**Closed by jpanther** 2020-01-24 00:08 UTC
Labels: bug
