### ISSUE TITLE
Fast Replacable Lamps

### ISSUE THREAD

**Issue by dbiser99** [jpanther/dectorio#195] opened 2021-01-03 02:27 UTC
Would it be possible to make the glow lamps fast replaceable with the vanilla lamps. I'm not an expert and might be missing something, but I just tried it out and it would appear to just need the following line added to lamp.lua

lamp.fast_replaceable_group = "lamp"

Thanks

**Comment by jpanther** [comment] 2021-03-08 00:38
Thanks for the suggestion and sorry for the late reply. I'll check and see if lamps support fast replacing and will add this in if it does.

**Comment by dbiser99** [comment] 2021-03-08 02:36
Awesome! As long as some other mod I have didn't change something, it does work and that was the line of code I added to do it. Just thought it might be something other people might find useful too so I made the suggestion here. Thanks!

**Comment by jpanther** [comment] 2021-07-16 02:33
Just following up on this one... I've tried adding this to `lamp.lua` but when I try to fast replace in game it pops up with "Lamp is in the way"... were you doing something differently?

```lamp.fast_replaceable_group = "lamp"```

<img width="137" alt="Screen Shot 2021-07-16 at 12 32 48" src="https://user-images.githubusercontent.com/4462786/125882732-544aba8e-f610-42a4-9eb7-b526cf459fc7.png">

**Comment by dbiser99** [comment] 2021-07-17 03:40
Not that I can see. Here is what's in my lamp.lua and according to my notes, that was all I changed from your code. I also just checked in case it was something that got changed in the game recently and it still works for me.

-- entity/lamp

-- Add glowing coloured lamp
local lamp = util.table.deepcopy(data.raw["lamp"]["small-lamp"])
lamp.name = "dect-small-lamp-glow"
lamp.icon = "__Dectorio__/graphics/icons/small-lamp-glow.png"
lamp.icon_size = 64
lamp.icon_mipmaps = 1
lamp.minable.result = "dect-small-lamp-glow"
lamp.glow_size = 25
lamp.glow_color_intensity = 0.8
lamp.glow_render_mode = "multiplicative"
lamp.light_when_colored.size = 0
lamp.light_when_colored.intensity = 0
lamp.fast_replaceable_group = "lamp"
data:extend({lamp})

**Comment by jpanther** [comment] 2021-09-08 00:12
Okay I finally worked out what the issue is here! The base lamp needs to be added to the group too. Not sure if this is something that you were doing somewhere (or maybe you had a mod installed that was doing this so you didn't realise) but if I add `data.raw["lamp"]["small-lamp"].fast_replaceable_group = "lamp"` it gets this to work. It will be included in the next Dectorio release.

**Closed** 2021-09-08 00:14 UTC
Labels: enhancement
