### ISSUE TITLE
desyncs in MP when placing signs

### ISSUE THREAD

**Issue by Xelan255** [jpanther/Dectorio#71] opened 2018-05-26 13:00 UTC
Hi there,
I recently startet a new Factorio run with a friend of mine on a headless server and this time around we decided to add Dectorio to our setup.The first few sessions everything went fine, but yesterday I tried to use one of the (btw awesome) signs to mark the contents of a chest, like my friend did earlier. "Tried to use" because when I placed the sign I got desynced from the server. After login back in again I still had the GUI for the sign symbol in my face, but everytime I selected something I got desynced again (and everyone else on the server as well).
Unfortunately the desync reports are about 50MB in size, which is why I had to upload them somewhere else:
https://www.dropbox.com/s/c7f2rc38d7qjpit/desync-report-2018-05-25_18-53-29.zip?dl=0
https://www.dropbox.com/s/3lers637yzbaq80/desync-report-2018-05-25_18-55-04.zip?dl=0
https://www.dropbox.com/s/rab75o5oq4q5of9/desync-report-2018-05-25_18-56-59.zip?dl=0

I have four more reports, but I guess they will say the same as these three. If you would like to take a look at them nonetheless, just say the word.

We did some testing after this occured:
- happens only in multiplayer
- doesn't matter who places a sign, always desyncs for both
- sometimes the sign was actually placed in the world after being desynced with the server, sometimes not. But the GUI was always open upon login back in, forcing you to click _something_ and getting desynced all over again.
- if the sign was placed in the world it was unremovable

**Comment by ShinoHarvest** [comment] 2018-05-26 13:08
confirmed

**Comment by jpanther** [comment] 2018-05-27 00:14
Thanks for the detailed report, and for taking the time to log this issue. It's often hard to debug these problems and when no one reports them they can go unnoticed for some time. I'll do some investigating to see if I can work out what is causing this desync. I don't have an easy way to test MP issues as it introduces a lot of variables and there's no easy way to simulate a MP environment without finding people to actually test it out in game (and that can be quite tedious for everyone). There has been a similar problem with signs in MP in the past so perhaps one of the recent updates has reintroduced the same issue.

In the meantime, a quick workaround to avoid this situation is to uncheck the "Enable signs" option in the Dectorio mod settings. That will hopefully allow you to continue to play while I look into a solution.

**Comment by Xelan255** [comment] 2018-05-27 07:56
Good to know you are working on it now :)
To reproduce this you don't actually need other people, just a headless server (which counts as a player of sorts, factorio-wise) since you get desynced regardless of others players in the lobby. I think the desync report contains the current savegame (if not I can upload one) so you could use that on a server and you should get the same desyncs as we did.
As for the workaround, yeah we simply don't use signs anymore. The older ones from earlier in the save (where they strangely still worked as intented) continue in doing their jobs and are.. well.. there :)

**Comment by jpanther** [comment] 2018-05-27 23:10
It is strange that this issue only appeared after some time playing. Do you know if the signs that did work were placed on a different base version of Factorio? It might help narrow down the potential cause.

**Comment by Xelan255** [comment] 2018-05-28 07:13
Thanks for the quick work :) _But_ unfortunately it doesn't work, instead it crashes the server with 

> Error ServerMultiplayerManager.cpp:96: MultiplayerManager failed: "First argument must be a number, table or string.
stack traceback:
	__Dectorio__/control.lua:329: in main chunk"
Full crashlog:
[dectorio server crashlog.zip](https://github.com/jpanther/Dectorio/files/2044052/dectorio.server.crashlog.zip)

**Comment by jpanther** [comment] 2018-05-28 07:41
Okay, that is less than ideal! I tested this on my own local server and it all worked fine. Is the save file you're using the same as the one you posted in your desync report? I tested with that one and it managed to load.

**Comment by Xelan255** [comment] 2018-05-28 07:47
Yeah, it's the same. I guess you also replicated our mod setup? Might be some of the other mods somehow interfering.
I played some time since then, so here is the latest save. 

[backup save1.zip](https://github.com/jpanther/Dectorio/files/2044150/backup.save1.zip)

**Comment by jpanther** [comment] 2018-05-28 08:15
Okay, I think it's something specific to when it loads an existing save for the first time with the new Dectorio on the headless server. Although even when I open that most recent save in a local game I get errors from Personal Teleporter: 

> __PersonalTeleporter__/control.lua:712: attempt to index field '?' (a nil value)

I'll have to do some more testing with the headless server. I suspect it's because the game treats the headless server as player 0 and so it might be trying to run some of the new fixes against that player.

**Comment by Xelan255** [comment] 2018-05-28 08:20
okay. In case you aren't sure: the headless server most definitely is player zero (or player one since I createt the save locally and then uploaded it to the server). Didn't see an error with personal teleporter yet on my site, but then again, I wasn't looking. No apparent problems with it so far either aside from the GUI element constantly being there.

**Comment by jpanther** [comment] 2018-05-28 23:20
Well this is a strange one. The Personal Teleporter error was a red herring. Turns out that mod references everything by Player Name rather than Player ID so it was erroring when I opened your save because my player name is different to yours. Seems like an odd way of doing things, but whatever. Strangely when I open the save locally the Personal Teleporter GUI is stuck open, but when I run headless it works fine. Go figure.

That aside, I still can't reproduce the startup error you were seeing. When I load up your latest save on my headless server it starts up fine and I can join and play your game. When I place a sign, though, it does still desync me. However, when I reconnect after being dropped, the game resumes fine (ie. you don't get stuck on the select an icon GUI) so I guess that is some progress. I'm wondering if there's something in the save that is specific to one of your players that is causing it to lock up.

To be sure, I created a brand new map that was generated on my headless server using the same modpack as your game. I joined and enabled cheat mode, crafted a few signs and placed them on the map with no desyncs. To try to force a desync I even placed a sign (so the icon GUI was showing) and then saved and quit before picking an icon. When I rejoined, the game took me straight to the map without any GUI in the way, and it had removed the sign I had placed without an icon. So from that perspective I think it is working although I haven't been able to test with more than just my player joining.

I'm thinking it's therefore something that has happened in your save file with the previous version of the mod that is still conflicting and until it gets cleaned up it wont fix itself. Do you have the same issues if you copy your headless save to your local game and try running it there? If that works, you may be able to re-save it locally and copy it back to the headless server and trick it into to working.

**Comment by Xelan255** [comment] 2018-05-29 05:37
Turns out the save crashes locally with the same error using Dectorio 0.8.9.. As for your testing: The strange thing is everything, including the signs, worked fine for the first x hours of the game. We even still have some of those early placed signs around to visually mark chests and their contents. I then played a while alone on the server and when I wanted to place a new sign to pick up our method of marking things with pretty signs I stumbled upon the desync bug. 
No idea what might be causing this. Researched technologies doesn't make any sense since the sign gives you all the icons to choose from anyway instead of just those items you have researched. The only other thing that changed that I can think of is game progress or base expansion but I don't see how that could possibly relate to anything. I don't have a special symbol in my username, neither does my friend.

**Comment by jmurrayufo** [comment] 2018-09-08 16:45
Got this same issue with our modpack. The moment any of us place a sign, instant desync. We are currently just asking people never to use signs, and might consider forking the mod to remove them to allow us to keep using this mod in our pack. 

Desync Report: https://drive.google.com/open?id=1QTLsYdNrKV9Umb3V7x8nf6lO5wsY15Ua
Mods Zip: https://drive.google.com/open?id=1FYOU8Fy_iDDkbX3KykH4JwTWuPX7JSUc

Happened early on in the game, saw that a patch had come out so we updated in the hopes of it being fixed. 8.9.0 has the same issues.

Server hosted on a headless setup on both hardware and a virtual machine (both running debian) resulted in the same issue. 

- Connect to MP (my test was just me, over LAN on a headless host.)
- Place metal sign
- Grid displays with items, followed by a crash before I can interact. 

Happy to help provide debug and more info if I can! This mod is great to play with!

**Comment by jmurrayufo** [comment] 2018-09-09 23:27
Can you disable them on an already running map? I thought that was only at map spawn that the setting took effect?

**Comment by jpanther** [comment] 2018-09-09 23:44
Yes, (although not ideal) you can do it on an existing save. It will simply hard delete any existing items that you already have on the map, in inventory, technology, etc. Obviously, make sure you have a backup of your save just in case it does something weird.

I think one of the possible issues you might be having with the signs given you have upgraded from an older version of Dectorio is that a lot of the fixes I made in the later release to avoid some desyncs might not fully clean up things that were left over from the previous saves. I have a feeling if it were a new map starting with 8.9.0, you possibly wont have the desync issue. But I still need to do more testing. I suspect if you disable signs altogether, you can at least avoid people accidentally placing a sign and desyncing your server!

**Comment by jmurrayufo** [comment] 2018-09-10 22:34
Will try to recreate on a fresh 8.9.0 map tonight!

**Comment by jpanther** [comment] 2019-02-27 02:15
Closing due to no further discussion.

**Closed by jpanther** 2019-02-27 02:15 UTC
Labels: bug
