### ISSUE TITLE
I'm using text plate from Earendal mod, got a crash with dectorio

### ISSUE THREAD

**Issue by Maxoxpower** [jpanther/dectorio#246] opened 2024-11-04 00:45 UTC
when i try to place a tile from earendal mod . 
i got a crash with dectorio

Error while running event Dectorio::on_built_entity (ID 6)
__Dectorio__/control.lua:155: attempt to index local 'entity' (a nil value)
stack traceback:
	__Dectorio__/control.lua:155: in function 'destroy_decoratives_near_entity'
	__Dectorio__/control.lua:163: in function <__Dectorio__/control.lua:162>

**Comment by Paksarra** [comment] 2024-11-04 02:40
I'm getting the same crash; I also have Text Plate installed.

**Comment by Vystella** [comment] 2024-11-04 03:03
Hello, same here.
When I try to build any entity, the same error message appears and the game crashes.
Until the problem is resolved, I have disabled the option "Remove decoratives near newly placed entities", this is how it currently works for me.

**Comment by jpanther** [comment] 2024-11-04 22:03
Thanks, I've been able to reproduce this. Fixed in #254 and will be in the next mod update.

**Closed** 2024-11-04 22:07 UTC
Labels: bug
