### ISSUE TITLE
Contruct (and blueprint) cliffs

### ISSUE THREAD

**Issue by The-Grim-Sleeper** [jpanther/dectorio#212] opened 2021-11-11 16:25 UTC
I saw 'Brok010's Blueprintable trees and rocks'-request and wanted to tac on cliffs there as well.
But we can't actually build cliffs at all as of yet.

**Comment by jpanther** [comment] 2022-06-23 05:01
Duplicate of #199

**Closed by jpanther** 2022-06-23 05:01 UTC
Labels: enhancement
