### ISSUE TITLE
Lamp conflict with Picker Tweaks mod

### ISSUE THREAD

**Issue by Fizzbin10** [jpanther/Dectorio#49] opened 2017-12-16 16:15 UTC
See error attached.

![image](https://user-images.githubusercontent.com/34604303/34072248-93bf14e2-e27b-11e7-8823-4528645fdb49.png)

I'm not using any mods that I'm aware would conflict with Dectorio.

**Comment by jpanther** [comment] 2017-12-17 05:46
Thanks for the report, I've tested Dectorio on 0.16.4 and am not getting the same error. Can you post a list of the other mods you're using and I'll see if it offers any clues.

**Comment by Fizzbin10** [comment] 2017-12-17 19:02
Sorry for the delay, will post list of mods within the next couple of hours.

**Comment by Fizzbin10** [comment] 2017-12-17 21:39
List of running mods below:

Auto Deconstruct.
BitersBegone!
Blueprint Flipper and Turner.
Bottleneck.
Even Distribution.
Long Inserters.
Miniloader.
Nanobots: Early Bots.
Picker Extended.
Picker Tweaks.
Side Inserters.
Timetools.
Upgrade Planner and Builder.

**Also installed but not active because they are not updated for 0.16.x are:**
Bob's adjustable inserters.
Burnys Train Station Blueprint Creator.
**Color Picker** - I uninstalled this one in case there was a conflict but the error remains.

Regards

**Comment by jpanther** [comment] 2017-12-17 21:46
Hmm thanks, I can replicate the error now and it's something conflicting with Picker Tweaks. I'll have a look and see if I can work out what the problem is.

**Comment by Fizzbin10** [comment] 2017-12-17 21:51
Thanks for ur work :)

**Comment by jpanther** [comment] 2017-12-17 22:00
This Picker Tweaks is quite a beast! Believe it or not it actually includes the Expanded Color Lamps mod within it and that mod is a known conflicting mod with Dectorio. Unfortunately there doesn't seem to be a setting in Picker Tweaks to disable the lamp changes part. The best workaround I have for you at the moment would be to disable Picker Tweaks and enable Dectorio, then go into the Mod Settings and uncheck the "Enable Signals" option under Dectorio startup settings. Then go back and re-enable Picker Tweaks. This will stop the conflicting part but you obviously won't get the extra signals from Dectorio. I'll let Nexela know about the conflict and see if he can add a setting in Picker Tweaks to prevent the issue from happening.

**Comment by Fizzbin10** [comment] 2017-12-18 00:09
Thanks very much for taking the time to research/formulate a solution to the problem, I did wonder if the if coloured signals were the problem and did play about with the settings but I couldn't make it work. I'll do as you advise and watch out for updates to either mod.

Thanks again.
Regards

**Comment by jpanther** [comment] 2017-12-18 00:35
Dectorio 0.8.1 will no longer crash when Picker Tweaks is installed, however it still won't actually prevent the issue where the lamp entities are being modified. Dectorio will now warn about this in-game and a future update to Picker Tweaks will allow the Expanded Color Lamps component to be toggled off, which will ultimately resolve the conflict. Thanks again for pointing this one out!

**Comment by Fizzbin10** [comment] 2017-12-18 00:37
Ur welcome jpanther, thanks again.

Regards
Fizz

**Comment by jpanther** [comment] 2017-12-18 03:34
Fixed in e7fb32a66e2f16963bf7f0780f13ccf30e7c80b0. Dectorio 0.8.1 is now live on the [Mod Portal](https://mods.factorio.com/mods/PantherX/Dectorio).

**Comment by jpanther** [comment] 2017-12-21 00:14
A quick update on this - Nexela has now added the option to turn off the lamps component in Picker Tweaks. You just need to untick the "Better Colored Lamps" option in Picker Tweaks mod startup settings. Once you do that, you can safely turn the "Enable Signals" option back on in Dectorio and the two mods will play nicely together.

Note that this will currently cause an incompatibility notification to appear, but I'll adjust it in a future update to Dectorio so that it only shows if you have the "Better Colored Lamps" setting switched on. I'll reopen this issue until that change is made.

Ref: Nexela/PickerTweaks#3

**Closed** 2017-12-27 00:00 UTC
Labels: incompatibility
