### ISSUE TITLE
Error with Alien Biomes

### ISSUE THREAD

**Issue by CrudePixels** [jpanther/Dectorio#99] opened 2019-03-28 12:22 UTC
Dectorio Seems to conflict with Alien Biomes.

![sad](https://user-images.githubusercontent.com/49028623/55157373-96b26880-5132-11e9-85a4-965ec04057e9.png)
[](url)

Here is Earendel's Response to the conflict
https://mods.factorio.com/mod/alien-biomes/discussion/5c86695ee20946000cf099e4

**Comment by jpanther** [comment] 2019-03-28 21:17
Thanks for the report. I'm unable to replicate your error, can you please provide the steps required to duplicate it.

The mod portal discussion you linked to is an error which was fixed in Dectorio 0.9.6. What versions of Dectorio and _Alien Biomes_ are you using?

**Comment by CrudePixels** [comment] 2019-03-28 22:49
It wont allow the game to start up at all without disabling the mod.

I'm on the latest factorio experimental version 0.17.21 
I believe I'm on the latest dectorio version and alien biome versions as well I can check when I get home in the morning.
Both mods work fine independently of each other but cant be enabled at the same time.

**Comment by jpanther** [comment] 2019-03-28 22:53
Are you using any other mods?

**Comment by CrudePixels** [comment] 2019-03-29 02:57
Yes, once I get home I will disable all other mods besides your mod and alien biome and double check. But your mod works with all the other mods I have and so does alien biome but they dont work together.

**Comment by CrudePixels** [comment] 2019-03-29 12:51
I was just prompted to update dectorio and it seems to have solved the problem,
It now works with alien biomes. I enabled all mods and it works with them still so all seems to be good,

**Closed** 2019-03-29 12:51 UTC
Labels: bug

**Comment by jpanther** [comment] 2019-03-29 23:24
Okay, thanks for letting me know. If the update fixed it you must have been playing with the _Arborium_ mod.

**Comment by jpanther** [comment] 2019-03-29 23:25
Duplicate of #100.
